version: '3.8'
services:
  web-financeiro:
    container_name: web-financeiro
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
      target: base
    ports:
      - "3000:3000"
    expose:
      - '3000'
    volumes:
      - ./frontend/:/usr/src/app/
      - /usr/src/app/node_modules

  server-financeiro:
    container_name: server-financeiro
    build:
      context: .
      dockerfile: ./backend/Dockerfile
      target: base
    depends_on:
      - postgres
    ports:
      - "3333:3333"
    expose:
      - '3333'
    volumes:
      - ./backend/:/usr/src/app/
      - /usr/src/app/node_modules
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"
    expose:
      - '5432'